import React from "react";
import { SmileOutlined } from "@ant-design/icons";
import { Timeline, Button } from "antd";

const Xiaoshou = () => {
  const data = {
    warningResultId: "173f99c2930e403792513389d9a8a1ea",
    pushTime: "2023-05-23T11:23:31",
    title: "小天鹅近1天负面消息数量环比超过阈值",
    content: {
      type: "MESSAGE",
      projectEmotionLevel: 4,
      escore: ["-1"],
      cTimeStartTime: "2023-05-22 11:23:00",
      cTimeEndTime: "2023-05-23 11:23:00",
      choseLevel: 1,
      hitValues: [
        {
          warningObjectId: "",
          name: "小天鹅",
          value: "小天鹅",
          hitValue: "25.00%",
          threshold: "0%",
          level: 1,
          other: "50%",
          children: [
            {
              warningObjectId: "",
              name: "小天鹅-1-1",
              value: "小天鹅-1-1",
              hitValue: "10.00%",
              threshold: "0%",
              level: 2,
              other: "50%",
              children: [
                {
                  warningObjectId: "",
                  name: "小天鹅-2-1",
                  value: "小天鹅-2-1",
                  hitValue: "5.00%",
                  threshold: "0%",
                  level: 3,
                  other: "50%",
                  children: [
                    {
                      warningObjectId: "",
                      name: "小天鹅-3-1",
                      value: "小天鹅-3-1",
                      hitValue: "5.00%",
                      threshold: "0%",
                      level: 4,
                      other: "50%",
                      children: [],
                    },
                  ],
                },
              ],
            },
            {
              warningObjectId: "",
              name: "小天鹅-1-2",
              value: "小天鹅-1-2",
              hitValue: "10.00%",
              threshold: "0%",
              level: 2,
              other: "50%",
              children: [
                {
                  warningObjectId: "",
                  name: "小天鹅-2-2",
                  value: "小天鹅-2-2",
                  hitValue: "8.00%",
                  threshold: "0%",
                  level: 3,
                  other: "50%",
                  children: [],
                },
              ],
            },
          ],
        },
        {
          warningObjectId: "",
          name: "大天鹅",
          value: "大天鹅",
          hitValue: "30.00%",
          threshold: "0%",
          level: 1,
          other: "60%",
          children: [
            {
              warningObjectId: "",
              name: "大天鹅-1-1",
              value: "大天鹅-1-1",
              hitValue: "10.00%",
              threshold: "0%",
              level: 2,
              other: "50%",
              children: [],
            },
          ],
        },
      ],
    },
  };

  const data2 = {
    warningResultId: "173f99c2930e403792513389d9a8a1ea",
    pushTime: "2023-05-23T11:23:31",
    title: "小米MAX等3个品牌近7天有无分屏等13个负面指标占比其他对象超过阈值",
    content: {
      type: "MESSAGE",
      projectEmotionLevel: 4,
      escore: ["-1"],
      cTimeStartTime: "2023-05-22 11:23:00",
      cTimeEndTime: "2023-05-23 11:23:00",
      choseLevel: 1,
      hitValues: [
        {
          warningObjectId: "",
          name: "服务配置",
          value: "服务配置",
          hitValue: "10",
          threshold: "0%",
          level: 1,
          other: "50%",
          children: [
            {
              warningObjectId: "",
              name: "售前",
              value: "售前",
              hitValue: "8",
              threshold: "0%",
              level: 2,
              other: "50%",
              children: [
                {
                  warningObjectId: "",
                  name: "售前价格",
                  value: "售前价格",
                  hitValue: "5",
                  threshold: "0%",
                  level: 3,
                  other: "50%",
                  children: [],
                },
                {
                  warningObjectId: "",
                  name: "售前服务",
                  value: "售前服务",
                  hitValue: "2",
                  threshold: "0%",
                  level: 3,
                  other: "50%",
                  children: [],
                },
              ],
            },
            {
              warningObjectId: "",
              name: "售后",
              value: "售后",
              hitValue: "7",
              threshold: "0%",
              level: 2,
              other: "50%",
              children: [
                {
                  warningObjectId: "",
                  name: "售后价格",
                  value: "售后价格",
                  hitValue: "4",
                  threshold: "0%",
                  level: 3,
                  other: "50%",
                  children: [],
                },
                {
                  warningObjectId: "",
                  name: "售后服务",
                  value: "售后服务",
                  hitValue: "3",
                  threshold: "0%",
                  level: 3,
                  other: "50%",
                  children: [],
                },
              ],
            },
          ],
        },
        {
          warningObjectId: "",
          name: "产品质量",
          value: "产品质量",
          hitValue: "9",
          threshold: "0%",
          level: 1,
          other: "60%",
          children: [
            {
              warningObjectId: "",
              name: "音效",
              value: "音效",
              hitValue: "5",
              threshold: "0%",
              level: 2,
              other: "50%",
              children: [
                {
                  warningObjectId: "",
                  name: "高音",
                  value: "高音",
                  hitValue: "3",
                  threshold: "0%",
                  level: 3,
                  other: "50%",
                  children: [],
                },
                {
                  warningObjectId: "",
                  name: "低音",
                  value: "低音",
                  hitValue: "2",
                  threshold: "0%",
                  level: 3,
                  other: "50%",
                  children: [],
                },
              ],
            },
            {
              warningObjectId: "",
              name: "画质",
              value: "画质",
              hitValue: "7",
              threshold: "0%",
              level: 2,
              other: "50%",
              children: [],
            },
          ],
        },
      ],
    },
  };

  const data3 = {
    warningResultId: "a14342310e8c4916826c490c57feba51",
    pushTime: "2023-05-26T17:44:51",
    title:
      "贵艾朗等4个品牌近30天外观与材质等73个指标提及负面指标的消息数量固定值超过阈值",
    content: {
      type: "PROJECT_ASPECT",
      businessPointId: 237,
      cTimeStartTime: "2023-04-26 17:43:56",
      cTimeEndTime: "2023-05-26 17:43:56",
      choseLevel: 1,
      hitValues: [
        {
          warningObjectId: "",
          name: "外观与材质",
          value: "7592",
          hitValue: "382",
          threshold: "0",
          aspectHitTotal: "5728",
          negativeCount: "382",
          level: 1,
          children: [
            {
              warningObjectId: "",
              name: "面料做工",
              value: "7588",
              hitValue: "274",
              threshold: "0",
              aspectHitTotal: "5728",
              negativeCount: "274",
              level: 2,
              children: [
                {
                  warningObjectId: "",
                  name: "厚薄程度",
                  value: "19026",
                  hitValue: "243",
                  threshold: "0",
                  aspectHitTotal: "5728",
                  negativeCount: "243",
                  level: 3,
                  children: [],
                  pid: "7588",
                  type: "GLOBAL",
                },
                {
                  warningObjectId: "",
                  name: "面料材质",
                  value: "19028",
                  hitValue: "60",
                  threshold: "0",
                  aspectHitTotal: "5728",
                  negativeCount: "60",
                  level: 3,
                  children: [],
                  pid: "7588",
                  type: "GLOBAL",
                },
                {
                  warningObjectId: "",
                  name: "软硬程度",
                  value: "19025",
                  hitValue: "54",
                  threshold: "0",
                  aspectHitTotal: "5728",
                  negativeCount: "54",
                  level: 3,
                  children: [],
                  pid: "7588",
                  type: "GLOBAL",
                },
                {
                  warningObjectId: "",
                  name: "做工细节",
                  value: "19029",
                  hitValue: "8",
                  threshold: "0",
                  aspectHitTotal: "5728",
                  negativeCount: "8",
                  level: 3,
                  children: [],
                  pid: "7588",
                  type: "GLOBAL",
                },
                {
                  warningObjectId: "",
                  name: "安全性",
                  value: "19027",
                  hitValue: "4",
                  threshold: "0",
                  aspectHitTotal: "5728",
                  negativeCount: "4",
                  level: 3,
                  children: [],
                  pid: "7588",
                  type: "GLOBAL",
                },
                {
                  warningObjectId: "",
                  name: "车线工艺",
                  value: "19030",
                  hitValue: "1",
                  threshold: "0",
                  aspectHitTotal: "5728",
                  negativeCount: "1",
                  level: 3,
                  children: [],
                  pid: "7588",
                  type: "GLOBAL",
                },
              ],
              pid: "7592",
              type: "COMBINE",
            },
            {
              warningObjectId: "",
              name: "产品设计",
              value: "7571",
              hitValue: "80",
              threshold: "0",
              aspectHitTotal: "5728",
              negativeCount: "80",
              level: 2,
              children: [
                {
                  warningObjectId: "",
                  name: "尺码/尺寸",
                  value: "19037",
                  hitValue: "70",
                  threshold: "0",
                  aspectHitTotal: "5728",
                  negativeCount: "70",
                  level: 3,
                  children: [],
                  pid: "7571",
                  type: "GLOBAL",
                },
                {
                  warningObjectId: "",
                  name: "数量/规格",
                  value: "19034",
                  hitValue: "18",
                  threshold: "0",
                  aspectHitTotal: "5728",
                  negativeCount: "18",
                  level: 3,
                  children: [],
                  pid: "7571",
                  type: "GLOBAL",
                },
                {
                  warningObjectId: "",
                  name: "重量",
                  value: "19036",
                  hitValue: "8",
                  threshold: "0",
                  aspectHitTotal: "5728",
                  negativeCount: "8",
                  level: 3,
                  children: [],
                  pid: "7571",
                  type: "GLOBAL",
                },
                {
                  warningObjectId: "",
                  name: "实用性",
                  value: "19031",
                  hitValue: "1",
                  threshold: "0",
                  aspectHitTotal: "5728",
                  negativeCount: "1",
                  level: 3,
                  children: [],
                  pid: "7571",
                  type: "GLOBAL",
                },
                {
                  warningObjectId: "",
                  name: "是否齐全",
                  value: "19033",
                  hitValue: "1",
                  threshold: "0",
                  aspectHitTotal: "5728",
                  negativeCount: "1",
                  level: 3,
                  children: [],
                  pid: "7571",
                  type: "GLOBAL",
                },
                {
                  warningObjectId: "",
                  name: "是否摆放整齐",
                  value: "19032",
                  hitValue: "0",
                  threshold: "0",
                  aspectHitTotal: "5728",
                  negativeCount: "0",
                  level: 3,
                  children: [],
                  pid: "7571",
                  type: "GLOBAL",
                },
              ],
              pid: "7592",
              type: "COMBINE",
            },
            {
              warningObjectId: "",
              name: "基础质量",
              value: "7581",
              hitValue: "79",
              threshold: "0",
              aspectHitTotal: "5728",
              negativeCount: "79",
              level: 2,
              children: [
                {
                  warningObjectId: "",
                  name: "整体质量",
                  value: "19045",
                  hitValue: "65",
                  threshold: "0",
                  aspectHitTotal: "5728",
                  negativeCount: "65",
                  level: 3,
                  children: [],
                  pid: "7581",
                  type: "GLOBAL",
                },
                {
                  warningObjectId: "",
                  name: "掉毛",
                  value: "19041",
                  hitValue: "19",
                  threshold: "0",
                  aspectHitTotal: "5728",
                  negativeCount: "19",
                  level: 3,
                  children: [],
                  pid: "7581",
                  type: "GLOBAL",
                },
                {
                  warningObjectId: "",
                  name: "韧性",
                  value: "19044",
                  hitValue: "14",
                  threshold: "0",
                  aspectHitTotal: "5728",
                  negativeCount: "14",
                  level: 3,
                  children: [],
                  pid: "7581",
                  type: "GLOBAL",
                },
                {
                  warningObjectId: "",
                  name: "保质期",
                  value: "19046",
                  hitValue: "12",
                  threshold: "0",
                  aspectHitTotal: "5728",
                  negativeCount: "12",
                  level: 3,
                  children: [],
                  pid: "7581",
                  type: "GLOBAL",
                },
                {
                  warningObjectId: "",
                  name: "起球",
                  value: "19042",
                  hitValue: "3",
                  threshold: "0",
                  aspectHitTotal: "5728",
                  negativeCount: "3",
                  level: 3,
                  children: [],
                  pid: "7581",
                  type: "GLOBAL",
                },
                {
                  warningObjectId: "",
                  name: "异味",
                  value: "19043",
                  hitValue: "2",
                  threshold: "0",
                  aspectHitTotal: "5728",
                  negativeCount: "2",
                  level: 3,
                  children: [],
                  pid: "7581",
                  type: "GLOBAL",
                },
                {
                  warningObjectId: "",
                  name: "尿显",
                  value: "19039",
                  hitValue: "1",
                  threshold: "0",
                  aspectHitTotal: "5728",
                  negativeCount: "1",
                  level: 3,
                  children: [],
                  pid: "7581",
                  type: "GLOBAL",
                },
                {
                  warningObjectId: "",
                  name: "漏晶体",
                  value: "19038",
                  hitValue: "1",
                  threshold: "0",
                  aspectHitTotal: "5728",
                  negativeCount: "1",
                  level: 3,
                  children: [],
                  pid: "7581",
                  type: "GLOBAL",
                },
                {
                  warningObjectId: "",
                  name: "凸点",
                  value: "19040",
                  hitValue: "0",
                  threshold: "0",
                  aspectHitTotal: "5728",
                  negativeCount: "0",
                  level: 3,
                  children: [],
                  pid: "7581",
                  type: "GLOBAL",
                },
              ],
              pid: "7592",
              type: "COMBINE",
            },
            {
              warningObjectId: "",
              name: "颜值",
              value: "7591",
              hitValue: "4",
              threshold: "0",
              aspectHitTotal: "5728",
              negativeCount: "4",
              level: 2,
              children: [
                {
                  warningObjectId: "",
                  name: "外观美观度",
                  value: "19048",
                  hitValue: "6",
                  threshold: "0",
                  aspectHitTotal: "5728",
                  negativeCount: "6",
                  level: 3,
                  children: [],
                  pid: "7591",
                  type: "GLOBAL",
                },
                {
                  warningObjectId: "",
                  name: "版型/裤型",
                  value: "19047",
                  hitValue: "1",
                  threshold: "0",
                  aspectHitTotal: "5728",
                  negativeCount: "1",
                  level: 3,
                  children: [],
                  pid: "7591",
                  type: "GLOBAL",
                },
              ],
              pid: "7592",
              type: "COMBINE",
            },
          ],
          pid: "-1",
          type: "COMBINE",
        },
        {
          warningObjectId: "",
          name: "使用体验",
          value: "7637",
          hitValue: "82",
          threshold: "0",
          aspectHitTotal: "5728",
          negativeCount: "82",
          level: 1,
          children: [
            {
              warningObjectId: "",
              name: "整体使用感",
              value: "7621",
              hitValue: "57",
              threshold: "0",
              aspectHitTotal: "5728",
              negativeCount: "57",
              level: 2,
              children: [
                {
                  warningObjectId: "",
                  name: "防漏性能",
                  value: "19010",
                  hitValue: "21",
                  threshold: "0",
                  aspectHitTotal: "5728",
                  negativeCount: "21",
                  level: 3,
                  children: [],
                  pid: "7621",
                  type: "GLOBAL",
                },
                {
                  warningObjectId: "",
                  name: "气味",
                  value: "19019",
                  hitValue: "16",
                  threshold: "0",
                  aspectHitTotal: "5728",
                  negativeCount: "16",
                  level: 3,
                  children: [],
                  pid: "7621",
                  type: "GLOBAL",
                },
                {
                  warningObjectId: "",
                  name: "吸收能力",
                  value: "19012",
                  hitValue: "15",
                  threshold: "0",
                  aspectHitTotal: "5728",
                  negativeCount: "15",
                  level: 3,
                  children: [],
                  pid: "7621",
                  type: "GLOBAL",
                },
                {
                  warningObjectId: "",
                  name: "起坨",
                  value: "19017",
                  hitValue: "5",
                  threshold: "0",
                  aspectHitTotal: "5728",
                  negativeCount: "5",
                  level: 3,
                  children: [],
                  pid: "7621",
                  type: "GLOBAL",
                },
                {
                  warningObjectId: "",
                  name: "透气性",
                  value: "19015",
                  hitValue: "4",
                  threshold: "0",
                  aspectHitTotal: "5728",
                  negativeCount: "4",
                  level: 3,
                  children: [],
                  pid: "7621",
                  type: "GLOBAL",
                },
                {
                  warningObjectId: "",
                  name: "含水量",
                  value: "19014",
                  hitValue: "4",
                  threshold: "0",
                  aspectHitTotal: "5728",
                  negativeCount: "4",
                  level: 3,
                  children: [],
                  pid: "7621",
                  type: "GLOBAL",
                },
                {
                  warningObjectId: "",
                  name: "粘性",
                  value: "19020",
                  hitValue: "4",
                  threshold: "0",
                  aspectHitTotal: "5728",
                  negativeCount: "4",
                  level: 3,
                  children: [],
                  pid: "7621",
                  type: "GLOBAL",
                },
                {
                  warningObjectId: "",
                  name: "弹性",
                  value: "19021",
                  hitValue: "3",
                  threshold: "0",
                  aspectHitTotal: "5728",
                  negativeCount: "3",
                  level: 3,
                  children: [],
                  pid: "7621",
                  type: "GLOBAL",
                },
                {
                  warningObjectId: "",
                  name: "反渗",
                  value: "19011",
                  hitValue: "3",
                  threshold: "0",
                  aspectHitTotal: "5728",
                  negativeCount: "3",
                  level: 3,
                  children: [],
                  pid: "7621",
                  type: "GLOBAL",
                },
                {
                  warningObjectId: "",
                  name: "连抽",
                  value: "19018",
                  hitValue: "3",
                  threshold: "0",
                  aspectHitTotal: "5728",
                  negativeCount: "3",
                  level: 3,
                  children: [],
                  pid: "7621",
                  type: "GLOBAL",
                },
                {
                  warningObjectId: "",
                  name: "润",
                  value: "19013",
                  hitValue: "2",
                  threshold: "0",
                  aspectHitTotal: "5728",
                  negativeCount: "2",
                  level: 3,
                  children: [],
                  pid: "7621",
                  type: "GLOBAL",
                },
                {
                  warningObjectId: "",
                  name: "跑杯/移位",
                  value: "19016",
                  hitValue: "0",
                  threshold: "0",
                  aspectHitTotal: "5728",
                  negativeCount: "0",
                  level: 3,
                  children: [],
                  pid: "7621",
                  type: "GLOBAL",
                },
              ],
              pid: "7637",
              type: "COMBINE",
            },
            {
              warningObjectId: "",
              name: "整体穿着体验",
              value: "7632",
              hitValue: "25",
              threshold: "0",
              aspectHitTotal: "5728",
              negativeCount: "25",
              level: 2,
              children: [
                {
                  warningObjectId: "",
                  name: "舒适度",
                  value: "19003",
                  hitValue: "28",
                  threshold: "0",
                  aspectHitTotal: "5728",
                  negativeCount: "28",
                  level: 3,
                  children: [],
                  pid: "7632",
                  type: "GLOBAL",
                },
                {
                  warningObjectId: "",
                  name: "红屁屁",
                  value: "19001",
                  hitValue: "9",
                  threshold: "0",
                  aspectHitTotal: "5728",
                  negativeCount: "9",
                  level: 3,
                  children: [],
                  pid: "7632",
                  type: "GLOBAL",
                },
                {
                  warningObjectId: "",
                  name: "不良反应",
                  value: "19000",
                  hitValue: "7",
                  threshold: "0",
                  aspectHitTotal: "5728",
                  negativeCount: "7",
                  level: 3,
                  children: [],
                  pid: "7632",
                  type: "GLOBAL",
                },
                {
                  warningObjectId: "",
                  name: "贴合身形程度",
                  value: "19004",
                  hitValue: "2",
                  threshold: "0",
                  aspectHitTotal: "5728",
                  negativeCount: "2",
                  level: 3,
                  children: [],
                  pid: "7632",
                  type: "GLOBAL",
                },
                {
                  warningObjectId: "",
                  name: "包容性",
                  value: "19007",
                  hitValue: "2",
                  threshold: "0",
                  aspectHitTotal: "5728",
                  negativeCount: "2",
                  level: 3,
                  children: [],
                  pid: "7632",
                  type: "GLOBAL",
                },
                {
                  warningObjectId: "",
                  name: "上身效果",
                  value: "19006",
                  hitValue: "1",
                  threshold: "0",
                  aspectHitTotal: "5728",
                  negativeCount: "1",
                  level: 3,
                  children: [],
                  pid: "7632",
                  type: "GLOBAL",
                },
                {
                  warningObjectId: "",
                  name: "束缚性",
                  value: "19008",
                  hitValue: "1",
                  threshold: "0",
                  aspectHitTotal: "5728",
                  negativeCount: "1",
                  level: 3,
                  children: [],
                  pid: "7632",
                  type: "GLOBAL",
                },
                {
                  warningObjectId: "",
                  name: "塑形美体",
                  value: "19005",
                  hitValue: "1",
                  threshold: "0",
                  aspectHitTotal: "5728",
                  negativeCount: "1",
                  level: 3,
                  children: [],
                  pid: "7632",
                  type: "GLOBAL",
                },
                {
                  warningObjectId: "",
                  name: "穿着体验",
                  value: "19009",
                  hitValue: "0",
                  threshold: "0",
                  aspectHitTotal: "5728",
                  negativeCount: "0",
                  level: 3,
                  children: [],
                  pid: "7632",
                  type: "GLOBAL",
                },
                {
                  warningObjectId: "",
                  name: "适配性",
                  value: "19002",
                  hitValue: "0",
                  threshold: "0",
                  aspectHitTotal: "5728",
                  negativeCount: "0",
                  level: 3,
                  children: [],
                  pid: "7632",
                  type: "GLOBAL",
                },
              ],
              pid: "7637",
              type: "COMBINE",
            },
            {
              warningObjectId: "",
              name: "使用便利度",
              value: "7636",
              hitValue: "4",
              threshold: "0",
              aspectHitTotal: "5728",
              negativeCount: "4",
              level: 2,
              children: [
                {
                  warningObjectId: "",
                  name: "便捷度",
                  value: "19024",
                  hitValue: "9",
                  threshold: "0",
                  aspectHitTotal: "5728",
                  negativeCount: "9",
                  level: 3,
                  children: [],
                  pid: "7636",
                  type: "GLOBAL",
                },
                {
                  warningObjectId: "",
                  name: "是否好穿",
                  value: "19022",
                  hitValue: "1",
                  threshold: "0",
                  aspectHitTotal: "5728",
                  negativeCount: "1",
                  level: 3,
                  children: [],
                  pid: "7636",
                  type: "GLOBAL",
                },
                {
                  warningObjectId: "",
                  name: "拆洗",
                  value: "19023",
                  hitValue: "0",
                  threshold: "0",
                  aspectHitTotal: "5728",
                  negativeCount: "0",
                  level: 3,
                  children: [],
                  pid: "7636",
                  type: "GLOBAL",
                },
              ],
              pid: "7637",
              type: "COMBINE",
            },
          ],
          pid: "-1",
          type: "COMBINE",
        },
        {
          warningObjectId: "",
          name: "功能设计",
          value: "7608",
          hitValue: "1",
          threshold: "0",
          aspectHitTotal: "5728",
          negativeCount: "1",
          level: 1,
          children: [
            {
              warningObjectId: "",
              name: "部位设计",
              value: "7607",
              hitValue: "1",
              threshold: "0",
              aspectHitTotal: "5728",
              negativeCount: "1",
              level: 2,
              children: [
                {
                  warningObjectId: "",
                  name: "整体设计",
                  value: "18990",
                  hitValue: "2",
                  threshold: "0",
                  aspectHitTotal: "5728",
                  negativeCount: "2",
                  level: 3,
                  children: [],
                  pid: "7607",
                  type: "GLOBAL",
                },
                {
                  warningObjectId: "",
                  name: "腰部设计",
                  value: "18989",
                  hitValue: "1",
                  threshold: "0",
                  aspectHitTotal: "5728",
                  negativeCount: "1",
                  level: 3,
                  children: [],
                  pid: "7607",
                  type: "GLOBAL",
                },
                {
                  warningObjectId: "",
                  name: "肩带",
                  value: "18992",
                  hitValue: "0",
                  threshold: "0",
                  aspectHitTotal: "5728",
                  negativeCount: "0",
                  level: 3,
                  children: [],
                  pid: "7607",
                  type: "GLOBAL",
                },
                {
                  warningObjectId: "",
                  name: "臀部设计",
                  value: "18988",
                  hitValue: "0",
                  threshold: "0",
                  aspectHitTotal: "5728",
                  negativeCount: "0",
                  level: 3,
                  children: [],
                  pid: "7607",
                  type: "GLOBAL",
                },
                {
                  warningObjectId: "",
                  name: "裆部设计",
                  value: "18987",
                  hitValue: "0",
                  threshold: "0",
                  aspectHitTotal: "5728",
                  negativeCount: "0",
                  level: 3,
                  children: [],
                  pid: "7607",
                  type: "GLOBAL",
                },
                {
                  warningObjectId: "",
                  name: "钢圈",
                  value: "18991",
                  hitValue: "0",
                  threshold: "0",
                  aspectHitTotal: "5728",
                  negativeCount: "0",
                  level: 3,
                  children: [],
                  pid: "7607",
                  type: "GLOBAL",
                },
              ],
              pid: "7608",
              type: "COMBINE",
            },
            {
              warningObjectId: "",
              name: "产品功能",
              value: "7600",
              hitValue: "0",
              threshold: "0",
              aspectHitTotal: "5728",
              negativeCount: "0",
              level: 2,
              children: [
                {
                  warningObjectId: "",
                  name: "清洁力",
                  value: "18993",
                  hitValue: "1",
                  threshold: "0",
                  aspectHitTotal: "5728",
                  negativeCount: "1",
                  level: 3,
                  children: [],
                  pid: "7600",
                  type: "GLOBAL",
                },
                {
                  warningObjectId: "",
                  name: "调节功能",
                  value: "18996",
                  hitValue: "0",
                  threshold: "0",
                  aspectHitTotal: "5728",
                  negativeCount: "0",
                  level: 3,
                  children: [],
                  pid: "7600",
                  type: "GLOBAL",
                },
                {
                  warningObjectId: "",
                  name: "抑味",
                  value: "18994",
                  hitValue: "0",
                  threshold: "0",
                  aspectHitTotal: "5728",
                  negativeCount: "0",
                  level: 3,
                  children: [],
                  pid: "7600",
                  type: "GLOBAL",
                },
                {
                  warningObjectId: "",
                  name: "收腹/塑形效果",
                  value: "18997",
                  hitValue: "0",
                  threshold: "0",
                  aspectHitTotal: "5728",
                  negativeCount: "0",
                  level: 3,
                  children: [],
                  pid: "7600",
                  type: "GLOBAL",
                },
                {
                  warningObjectId: "",
                  name: "聚拢",
                  value: "18998",
                  hitValue: "0",
                  threshold: "0",
                  aspectHitTotal: "5728",
                  negativeCount: "0",
                  level: 3,
                  children: [],
                  pid: "7600",
                  type: "GLOBAL",
                },
                {
                  warningObjectId: "",
                  name: "承托",
                  value: "18999",
                  hitValue: "0",
                  threshold: "0",
                  aspectHitTotal: "5728",
                  negativeCount: "0",
                  level: 3,
                  children: [],
                  pid: "7600",
                  type: "GLOBAL",
                },
                {
                  warningObjectId: "",
                  name: "裁剪功能",
                  value: "18995",
                  hitValue: "0",
                  threshold: "0",
                  aspectHitTotal: "5728",
                  negativeCount: "0",
                  level: 3,
                  children: [],
                  pid: "7600",
                  type: "GLOBAL",
                },
              ],
              pid: "7608",
              type: "COMBINE",
            },
          ],
          pid: "-1",
          type: "COMBINE",
        },
      ],
    },
  };

  const data4 = {
    warningResultId: "173f99c2930e403792513389d9a8a1ea",
    pushTime: "2023-05-23T11:23:31",
    title: "小米MAX等3个品牌近7天有无分屏等13个负面指标占比其他对象超过阈值",
    content: {
      type: "MESSAGE",
      projectEmotionLevel: 4,
      escore: ["-1"],
      cTimeStartTime: "2023-05-22 11:23:00",
      cTimeEndTime: "2023-05-23 11:23:00",
      choseLevel: 1,
      hitValues: [
        {
          warningObjectId: "",
          name: "服务配置",
          value: "服务配置",
          hitValue: "10",
          threshold: "0%",
          level: 1,
          other: "50%",
          children: [
            {
              warningObjectId: "",
              name: "售前",
              value: "售前",
              hitValue: "8",
              threshold: "0%",
              level: 2,
              other: "50%",
              children: [
                {
                  warningObjectId: "",
                  name: "售前价格",
                  value: "售前价格",
                  hitValue: "5",
                  threshold: "0%",
                  level: 3,
                  other: "50%",
                  children: [],
                },
                {
                  warningObjectId: "",
                  name: "售前服务",
                  value: "售前服务",
                  hitValue: "2",
                  threshold: "0%",
                  level: 3,
                  other: "50%",
                  children: [],
                },
              ],
            },
            {
              warningObjectId: "",
              name: "售后",
              value: "售后",
              hitValue: "17",
              threshold: "0%",
              level: 2,
              other: "50%",
              children: [
                {
                  warningObjectId: "",
                  name: "售后价格",
                  value: "售后价格",
                  hitValue: "54",
                  threshold: "0%",
                  level: 3,
                  other: "50%",
                  children: [],
                },
                {
                  warningObjectId: "",
                  name: "售后服务",
                  value: "售后服务",
                  hitValue: "3",
                  threshold: "0%",
                  level: 3,
                  other: "50%",
                  children: [],
                },
              ],
            },
          ],
        },
        {
          warningObjectId: "",
          name: "产品质量",
          value: "产品质量",
          hitValue: "9",
          threshold: "0%",
          level: 1,
          other: "60%",
          children: [
            {
              warningObjectId: "",
              name: "音效",
              value: "音效",
              hitValue: "15",
              threshold: "0%",
              level: 2,
              other: "50%",
              children: [
                {
                  warningObjectId: "",
                  name: "高音",
                  value: "高音",
                  hitValue: "3",
                  threshold: "0%",
                  level: 3,
                  other: "50%",
                  children: [],
                },
                {
                  warningObjectId: "",
                  name: "低音",
                  value: "低音",
                  hitValue: "2",
                  threshold: "0%",
                  level: 3,
                  other: "50%",
                  children: [],
                },
              ],
            },
            {
              warningObjectId: "",
              name: "画质",
              value: "画质",
              hitValue: "37",
              threshold: "0%",
              level: 2,
              other: "50%",
              children: [],
            },
          ],
        },
        {
          warningObjectId: "",
          name: "测试分支",
          value: "测试分支",
          hitValue: "20",
          threshold: "0%",
          level: 1,
          other: "60%",
          children: [
            {
              warningObjectId: "",
              name: "测试二级",
              value: "测试二级",
              hitValue: "13",
              threshold: "0%",
              level: 2,
              other: "50%",
              children: [
                {
                  warningObjectId: "",
                  name: "测试三级",
                  value: "测试三级",
                  hitValue: "100",
                  threshold: "0%",
                  level: 3,
                  other: "50%",
                  children: [],
                },
                {
                  warningObjectId: "",
                  name: "我也是测试三级",
                  value: "我也是测试三级",
                  hitValue: "2",
                  threshold: "0%",
                  level: 3,
                  other: "50%",
                  children: [],
                },
              ],
            },
            {
              warningObjectId: "",
              name: "我也是测试二级",
              value: "我也是测试二级",
              hitValue: "9",
              threshold: "0%",
              level: 2,
              other: "50%",
              children: [],
            },
            {
              warningObjectId: "",
              name: "我还是测试二级",
              value: "我还是测试二级",
              hitValue: "8",
              threshold: "0%",
              level: 2,
              other: "50%",
              children: [],
            },
          ],
        },
      ],
    },
  };
  const type = "one";
  const array = [
    "贵艾朗等4个品牌近30天产品设计等42个指标负面指标数量固定值超过阈值",
    "预警对象",
    "触发条件",
    "规则分类",
    "紧急程度",
    "数据类型",
    "预警类型",
    "推送时间",
  ];

  const fn = () => {
    console.log(111);
  };
  return <Button onClick={fn}>点击下载</Button>;
};

export default Xiaoshou;
